version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/{{ cookiecutter.project_slug }}"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/{{ cookiecutter.project_slug }}"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/{{ cookiecutter.project_slug }}"
    schedule:
      interval: "daily"
