version: "3.8"

services:
  app:
    image: "app:latest"
    container_name: "app"
    restart: always
    depends_on:
      - db
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: sh ./prod-start.sh
    env_file:
      - .env

  db:
    restart: always
