version: "3.8"

services:
  app:
    image: "restapi:dev"
    container_name: "restapi"
    restart: unless-stopped
    depends_on:
      - db
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/rest
    command: sh ./scripts/start-dev.sh
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    container_name: "restapi_db"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
