version: "3.8"

services:
  app:
    image: "restapi:latest"
    container_name: "restapi"
    restart: always
    depends_on:
      - db
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh ./scripts/start-prod.sh
    env_file:
      - .env

  db:
    image: "postgres:14-alpine"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  - pgdata:
